version: '3.9'

services:
  producer:
    build:
      context: .
      dockerfile: apps/producer/Dockerfile
    container_name: producer_service
    environment:
      - NODE_ENV=production
    ports:
      - "50052:50052"
    networks:
      - microservices_network

  consumer:
    build:
      context: .
      dockerfile: apps/consumer/Dockerfile
    container_name: consumer_service
    environment:
      - NODE_ENV=production
    ports:
      - "50051:50051"
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge
